[package]
name = "xdata"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_toml = "0.0.1"
serde_yaml = "0.9.34"
toml = "0.8.19"
